[package]
name = "egor00f/dialoglib"

description = "Libarary for creating dialogs"

version = "0.1.5"

registry = "https://github.com/UpliftGames/wally-index"

# or server
realm = "shared"

license = "MIT"

repository = "https://github/Ukuroks-Games/dialoglib"

authors = ["Egor00f <velikiydolbayeb@gmail.com>"]

private = false

[dependencies]


[server-dependencies]


[dev-dependencies]
